let aDescription = "<img alt='' src='https://i.amz.mshcdn.com/pkGGHincrxCzdPHRL6f4FcTzHg4=/575x323/filters:quality(90)/https%3A%2F%2Fblueprint-api-production.s3.amazonaws.com%2Fuploads%2Fcard%2Fimage%2F660128%2F26fe8e94-fa36-4972-bc39-c45b6290c180.jpg' /><div style='float: right; width: 50px;'><a href='https://twitter.com/share?via=Mashable&text=Twitter+apologises+for+accidentally+blocking+New+York+Times+account&url=http%3A%2F%2Fmashable.com%2F2017%2F11%2F27%2Ftwitter-new-york-times-block-mistake%2F' style='margin: 10px;'><img alt='Twitter' border='0' src='https://a.amz.mshcdn.com/assets/feed-tw-e71baf64f2ec58d01cd28f4e9ef6b2ce0370b42fbd965068e9e7b58be198fb13.jpg' /></a><a href='https://www.facebook.com/sharer.php?u=http%3A%2F%2Fmashable.com%2F2017%2F11%2F27%2Ftwitter-new-york-times-block-mistake%2F&src=sp' style='margin: 10px;'><img alt='Facebook' border='0' src='https://a.amz.mshcdn.com/assets/feed-fb-8e3bd31e201ea65385a524ef67519d031e6851071807055648790d6a4ca77139.jpg' /></a></div><p>Twitter is not new to making glaring mistakes in suspending or blocking the wrong people on the platform.&#160;</p> <div></div> <p>But this time it's quite massive.&#160;</p> <p>The social media platform apologised to the <em>New York Times</em> after it blocked its<a href='https://twitter.com/nytimesworld'> @nytimesworld </a>account for 24 hours after an alleged violation of Twitter's rules about hateful conduct.&#160;</p> <p>The account had tweeted a story about Canadian prime minister Justin Trudeau apologising to indigenous people in a Canadian province. Here's the tweet in question:</p> <div><div><blockquote> <p>Left out of an apology a decade ago, native people in Newfoundland and Labrador get an apology from Justin Trudeau <a href='https://t.co/BRRIUNCVMw'>https://t.co/BRRIUNCVMw</a></p> <p>&#8212; New York Times World (@nytimesworld) <a href='https://twitter.com/nytimesworld/status/934264664975867904?ref_src=twsrc%5Etfw'>November 25, 2017</a> <a href='http://mashable.com/2017/11/27/twitter-new-york-times-block-mistake/'>Read more...</a></p> </blockquote></div></div>More about <a href='http://mashable.com/category/twitter/'>Twitter</a>, <a href='http://mashable.com/category/new-york-times/'>New York Times</a>, <a href='http://mashable.com/category/blocking/'>Blocking</a>, <a href='http://mashable.com/category/twitter-account/'>Twitter Account</a>, and <a href='http://mashable.com/culture/'>Culture</a>";

// aDescription = aDescription.replace(/<img(.*?)\/>/g, ""); // remove any images in description <p>[\s]*</p>
// aDescription = aDescription.replace(/Read more.*/g, ""); // remove any div in description
// aDescription = aDescription.replace(/<a (.*?)>/g,"");
// aDescription = aDescription.replace(/<\/a>/g,"");
// aDescription = aDescription.replace(/<iframe (.*?)<\/iframe>/g,"");
// aDescription = aDescription.replace(/http(.?)[^<]*/g,"");
aDescription = aDescription.replace(/<div(.*?)>/g,"");
aDescription = aDescription.replace(/<\/div/g,"");

console.log(aDescription);
//console.log(string.replace(/<p\b[^>]*>SEE(.*?)<\/p>/gi, '');